name: Tiny-Agents CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set environment variables
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "HF_TOKEN is set"
          echo "GCP_CREDENTIALS is set"
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 agent.py app.py
      - name: Run basic script check (agent.py)
        run: |
          python agent.py --help || true
      - name: Run basic script check (app.py)
        run: |
          python -m py_compile app.py
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Authenticate gcloud
        run: |
          printf '%s' "${{ secrets.GCP_CREDENTIALS }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
      - name: Deploy to Google Cloud Run
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
            --source . \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
