name: Tiny-Agents CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set environment variables
        run: |
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV
          echo "GCP_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}" >> $GITHUB_ENV
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 agent.py
      - name: Run basic script check
        run: |
          python agent.py --help || true
